TaskTrack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from TaskTrack import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from accounts import views

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

app_name = 'accounts'

tasks/urls.py
from django.urls import path, include

from tasks import views

urlpatterns = [
    path('', views.TaskListView.as_view(), name='task-list'),
    path('create/', views.TaskCreateView.as_view(), name='task-create'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='task-update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='task-delete'),
    path('<int:pk>/comment/create', views.CommentCreateView.as_view(), name='comment-create'),

]

app_name = 'tasks'

accounts/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


# Create your models here.

class Task(models.Model):
    STATUS_CHOICES = [
        ('todo', 'To Do'),
        ('in_progress', 'In Progress'),
        ('done', 'Done')
    ]
    PRIORITY_CHOICES = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('urgent', 'Urgent')
    ]

    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='todo')
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES, default='medium')
    due_date = models.DateField(blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')
    executors = models.ManyToManyField(User, related_name='assigned_tasks')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
            return self.title


class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField(verbose_name="Your comment")
    created_at = models.DateTimeField(auto_now_add=True)
    media = models.FileField(upload_to='comment_media', blank=True, null=True)

    def __str__(self):
        return self.content

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

from tasks import models


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control mb-2', })

        self.fields['password'].widget = forms.PasswordInput(attrs={'class': 'form-control mb-2'})


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control mb-2', })

        self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control mb-2'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control mb-2'})

tasks/forms.py
from django import forms

from tasks import models


class TaskForm(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = ['title', 'description', 'status', 'priority', 'due_date']

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control mb-2', })

        self.fields['due_date'].widget = forms.DateInput(attrs={'class': 'form-control mb-2'})


class TaskFilterForm(forms.Form):
    STATUS_CHOICES = [
        ('', 'All'),
        ('todo', 'To Do'),
        ('in_progress', 'In Progress'),
        ('done', 'Done')
    ]

    status = forms.ChoiceField(choices=STATUS_CHOICES, required=False, label="Status")

    def __init__(self, *args, **kwargs):
        super(TaskFilterForm, self).__init__(*args, **kwargs)
        self.fields['status'].widget.attrs.update({'class': 'form-control', })


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['content', 'media']
        widgets = {'media': forms.FileInput(attrs={'type' : 'file', 'class' : 'form-control mb-2'})}
    def __init__(self, *args, **kwargs):
        super(CommentCreateForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control mb-2', })

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from accounts.forms import UserLoginForm, UserRegisterForm


# Create your views here.

class CustomLoginView(LoginView):
    template_name = 'accounts/login.html'
    redirect_authenticated_user = True
    form_class = UserLoginForm

class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('accounts:login')

class RegisterView(CreateView):
    template_name = 'accounts/register.html'
    form_class = UserRegisterForm
    success_url = 'accounts:login'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(reverse_lazy('tasks:task-list'))

tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from tasks import models
from tasks.forms import TaskForm, TaskFilterForm, CommentCreateForm
from tasks.mixins import UserIsExecutorMixin, UserIsOwnerMixin

# Create your views here.
class TaskListView(LoginRequiredMixin, ListView):
    model = models.Task
    context_object_name = 'tasks'
    template_name = 'tasks/task_list.html'

    def get_queryset(self):
        queryset = super(TaskListView, self).get_queryset()

        status = self.request.GET.get('status')
        if status:
            queryset = queryset.filter(status= status)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TaskFilterForm(self.request.GET)
        return context

class TaskCreateView(LoginRequiredMixin, CreateView):
    model = models.Task
    template_name = 'tasks/task_form.html'
    success_url = reverse_lazy('tasks:task-list')
    form_class = TaskForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, UserIsOwnerMixin, UpdateView):
    model = models.Task
    template_name = 'tasks/task_detail.html'
    success_url = reverse_lazy('tasks:task-list')
    form_class = TaskForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentCreateForm()
        return context

class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Task
    template_name = 'tasks/delete_confirmation.html'
    success_url = reverse_lazy('tasks:task-list')


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = models.Comment
    form_class = CommentCreateForm

    def get_success_url(self):
        return  reverse_lazy('tasks:task-update', kwargs={'pk': self.object.task.pk})

    def get_task(self):
        task_pk = self.kwargs.get('pk')
        return get_object_or_404(models.Task, pk=task_pk)

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.task = self.get_task()
        return super().form_valid(form)

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
   <div class="container">
   {% include 'alerts.html' %}
   <h1 class="text-center">Login</h1>
       <form method="post">
          {% csrf_token %}
            {{ form.as_div }}
           <button type="submit" class="btn btn-light"> Login </button>
 <a href="{% url 'accounts:register' %}" class="btn btn-outline-white">Register</a>
       </form>

   </div>

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
   <div class="container">
   {% include 'alerts.html' %}
   <h1 class="text-center">Register</h1>
       <form method="post">
          {% csrf_token %}
            {{ form.as_div }}
           <button type="submit" class="btn btn-light"> Register </button>
           <a href="{% url 'accounts:login' %}" class="btn btn-outline-white">Login</a>
       </form>

   </div>

{% endblock %}

templates/alerts.html
{% if messages %}
  {% for message in messages %}
        <div{% if message.tags %} class="alert {{ message.tags }}"{% endif %} role="alert">
            {{ message }}
        </div>
  {% endfor %}
{% endif %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BookingApp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body data-bs-theme="dark">
    <header class="mt-4 d-flex justify-content-center align-items-center">
        <a href="{% url 'tasks:task-list' %}" class="text-decoration-none text-white">
            <h1 class="text-center">TaskTrack</h1>
        </a>
        {% if request.user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
             <button type="submit" class="btn">
                    <i class="bi bi-box-arrow-right"></i>
              </button>
          </form>
        {% endif %}
    </header>
    <main  class="my-3 ">
        {% block content %}

        {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/tasks/delete_confirmation.html
{% extends 'base.html' %}

{% block content %}
   <div class="container">
   {% include 'alerts.html' %}
        <div class="d-flex justify-content-center align-items-center">
            <form method="post" class="">
          {% csrf_token %}
           <h3>Are you sure?</h3>
           <button class="btn btn-light" type="submit"> Yes, delete </button>
           <a href="{% url 'tasks:task-list' %}" class="btn btn-secondary"> No </a>
       </form>
        </div>

   </div>

{% endblock %}

templates/tasks/task_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    {% include 'alerts.html' %}

    <div class="row">
        <div class="col-md-8">
            <form method="post">
                {% csrf_token %}
                {{ form.as_div }}
                <button type="submit" class="btn btn-light"> Save</button>
                <a href="{% url 'tasks:task-delete' task.pk %}" class="btn btn-secondary">
                    Delete
                </a>
            </form>
        </div>
        <div class="col-md-4">

            <form action="{% url 'tasks:comment-create' task.pk %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ comment_form.as_div }}
                <button type="submit" class="btn btn-secondary">Add</button>
            </form>

            <h3>Comments</h3>

            {% for comment in task.comments.all %}
                <div class="my-1 p-2 card">
                     <h5>{{ comment.author.username }}:</h5>
                    <p>{{comment.content}}</p>
                    {% if comment.media %}
                        <a href="{{comment.media.url}}" class="mb-2 tex-white">Open file</a>
                    {% endif %}

                    <small>{{comment.created_at}}</small>

                </div>
            {% empty %}
            <p>No comments here.</p>
            {% endfor %}

        </div>
    </div>


</div>

{% endblock %}

templates/tasks/task_form.html
{% extends 'base.html' %}

{% block content %}
   <div class="container">
   {% include 'alerts.html' %}
   <h1 class="text-center">TaskTrack</h1>
       <form method="post">
          {% csrf_token %}
            {{ form.as_div }}
           <button type="submit"> Save </button>
       </form>

   </div>

{% endblock %}

templates/tasks/task_list.html
{% extends 'base.html' %}

{% block content %}
   <div class="container">
   {% include 'alerts.html' %}

       <a class="btn btn btn-outline-light my-3" href="{% url 'tasks:task-create' %}" role="button"><i class="bi bi-plus-square me-1"></i>New task</a>

       <form method="get" class="d-flex gap-3 align-items-end pb-2">
           {{form.as_div}}
           <button type="submit" class="btn btn-warning">Filter</button>
       </form>

       <div class="list-group">
        {% for task in tasks %}
           <a href="{% url 'tasks:task-update' task.pk %}" class="list-group-item list-group-item-action" aria-current="true">
               {{ task.title }}
               <span class="badge text-bg-primary">{{task.get_status_display  }}</span>
               <span class="badge text-bg-warning">{{task.get_priority_display }}</span>

         </a>
       {% endfor %}
    </div>


   </div>


{% endblock %}